baseURL = 'https://erdmko.dev/blog'
defaultContentLanguage = 'ru'
title = 'ErDmKo blog'
enableRobotsTXT = true
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
[Social]
    twitter = 'erdmko' 
[markup]
  [markup.highlight]
    lineNos = true
