---
- hosts: web
  name: static files push
  vars:
    install_dirr: '/opt/blog'
  tasks:
  - name: directory exist
    ansible.builtin.file:
      path: "{{ install_dirr }}"
      state: directory
  - name: push
    ansible.posix.synchronize:
      src: './../public'
      dest: '{{ install_dirr }}'
